# Generated by Django 6.1.1 on 2026-09-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='medio',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
